version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: clubes_exitus_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clubes_exitus
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
